### ISSUE TITLE
Can "guage" misspelling be fixed please?

### ISSUE THREAD

**Issue by pfalcon** [espruino/TinyDash#1]
I'd like to hack something with TinyDash, and the next thing after
~~~
  TD.label = function(opts) {
  TD.graph= function(opts) {
~~~
which trips me is "guage" spelled like that 8 times around (more at http://www.espruino.com/Web+Bluetooth+Dashboard).

Last time I checked, it still was "gauge": https://www.google.com/search?q=guage

Thanks for your great work!

**Comment by gfwilliams** [comment]
Eep. Can't believe I did that! Sure, will get that fixed

**Comment by pfalcon** [comment]
Thanks!
