### ISSUE TITLE
Problem with onchange in TD.value

### ISSUE THREAD

**Issue by baptiste-Mo** [espruino/TinyDash#2]
Hi, 
When I write  TD.value with an onChange parameter I have not a return for the value. I think it's because in tinyDash.value you call the function with sendChanges(el,el.pressed) and I think you should call sendChanges(el,v).
Regards

**Comment by gfwilliams** [comment]
Thanks! Think I just fixed this - maybe you could confirm?

**Comment by baptiste-Mo** [comment]
Thanks. Yes I confirm it's fixed.
